# Generated by Django 3.2.6 on 2021-08-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_fix', '0004_contact_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_requested',
            name='area_in',
        ),
        migrations.RemoveField(
            model_name='service_requested',
            name='service_required',
        ),
    ]
