# Generated by Django 3.2.6 on 2021-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_fix', '0012_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='service_requested',
            name='customer_contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
