# Generated by Django 3.2.6 on 2021-10-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_fix', '0013_auto_20210925_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_requested',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
