# Generated by Django 3.2.6 on 2021-11-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_fix', '0015_alter_contact_us_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
